name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: sistem-analizi/ci/.github/workflows/deploy.yml@v1
    with:
      build_type: node
      year: '2026'
      build_command: pnpm run generate
      output_dir: .output/public
      clean_slate: true
      build_env: |
        NUXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NUXT_PUBLIC_FIREBASE_API_KEY }}
        NUXT_PUBLIC_FIREBASE_DATABASE_URL=${{ secrets.NUXT_PUBLIC_FIREBASE_DATABASE_URL }}
        NUXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NUXT_PUBLIC_FIREBASE_PROJECT_ID }}
    secrets: inherit
